configserver:
    name: JHipster Registry config server
    status: Connected to the JHipster Registry config server, using https://github.com/qasanov/config-server !

# Default JWT secret token (to be changed in production!)
jhipster:
    security:
        authentication:
            jwt:
                secret: bXktc2VjcmV0LXRva2VuLXRvLWNoYW5nZS1pbi1wcm9kdWN0aW9uLWFuZC10by1rZWVwLWluLWEtc2VjdXJlLXBsYWNl
server :
    port: 7070
